### ISSUE TITLE
CookieBot Declaration

### ISSUE THREAD

**Issue by memignone** [yeutech-lab/react-cookiebot#11] opened 2020-04-17 15:19 UTC
Is it possible to use CookieBot's CookieDeclaration script with react?

I tried but this is the problem I have right now: https://www.agesciroma24.it/privacy/

This is the page's code:
```const PrivacyPage: React.FC = () => (
  <Layout
    seo={{
      title: 'Privacy',
    }}
  >
    <Header title="Privacy" />
    <script
      id="CookieDeclaration"
      src="https://consent.cookiebot.com/07b90fa4-8666-443b-97c2-ceb64919d2da/cd.js"
      type="text/javascript"
      defer
    />
  </Layout>
)```

**Comment by kopax** [comment] 2020-04-17 22:19
> Is it possible to use CookieBot's CookieDeclaration script with react?

Yes, this is the job of this react module. It is approved by cookie bot company,  I confirmed this work fine.

Note that if you use `react-cookiebot`, you don't need to use anything else than it.

See here the declaration script:

https://github.com/yeutech-lab/react-cookiebot/blob/ff40f6b306aad273a1356a0cf429f95a5f0ae938/src/CookieBot.js#L28

In order for cookie bot to work, you normally must use two scripts. 

- One must be the first script added in the head
- other (declaration) can be anywhere

This component will do both for you, and the declaration will be added exactly where you decide to render react cookiebot .

```jsx
<CookieBot domainGroupId={domainGroupId} />
```

Is enough.

I am closing but feel free to reply if you still have a question. (Or add a star) 

Thanks for your interest, 

Dimitri

**Comment by kopax** [comment] 2020-04-17 22:26
> 
> I tried but this is the problem I have right now: https://www.agesciroma24.it/privacy/
> 
> This is the page's code:
> 
> ```
>   <Layout
>     seo={{
>       title: 'Privacy',
>     }}
>   >
>     <Header title="Privacy" />
>     <script
>       id="CookieDeclaration"
>       src="https://consent.cookiebot.com/07b90fa4-8666-443b-97c2-ceb64919d2da/cd.js"
>       type="text/javascript"
>       defer
>     />
>   </Layout>
> )```
> ```

**Closed as completed by kopax** 2020-04-17 22:26 UTC
Labels: question

**Comment by lucavime** [comment] 2022-08-24 10:29
What if I want Declaration in another page?

`<CookieBot domainGroupId={domainGroupId} />`
should be added in App component, but declaration script in cookie policy page.

If I copy CookieBot component inside both pages my CookieBot script will duplicate in head. Am I right?

**Comment by MartinLindalHansen** [comment] 2023-05-26 14:18
I have the exact same issue here. 
The CookieBot component is added in App component (as should be).
But the CookieBot declaration text is supposed to be on the cookie policy page.

The documentation does not provide any solutions on the CookieBot Declaration - and adding the CookieBot component again, on the cookie policy page, results in an error/warning in the console: 
_"WARNING: Cookiebot script is included twice - please remove one instance to avoid unexpected results."_

**Comment by leslierhsw** [comment] 2023-06-05 19:30
> What if I want Declaration in another page?
> 
> `<CookieBot domainGroupId={domainGroupId} />` should be added in App component, but declaration script in cookie policy page.
> 
> If I copy CookieBot component inside both pages my CookieBot script will duplicate in head. Am I right?

My exact problem right now...

Any solution to set cookie declaration in a single page?

Update: I try to load the CookieDeclaration using a hook. It loads, but the entire Declaration content keeps loading at the top of the page, breaking the design. Cannot waste more time with this. My team will recommend to the architect to find another solution/product that is React, Razor, and/or Angular friendly.

**Comment by kopax-polyconseil** [comment] 2023-06-06 07:33
Any PR tu spport new feature are welcome !

**Comment by MartinLindalHansen** [comment] 2023-06-06 09:37
The declaration can be accessed inside the cookie pop-up, as far as I can tell - at any time, at any page.
Should suffice with regulations?

**Comment by leslierhsw** [comment] 2023-06-06 14:07
> Any PR tu spport new feature are welcome !

That ship has sailed, we already found another vendor.

**Comment by leslierhsw** [comment] 2023-06-06 14:10
> The declaration can be accessed inside the cookie pop-up, as far as I can tell - at any time, at any page. Should suffice with regulations?


This is the real issue: https://github.com/yeutech-lab/react-cookiebot/issues/11#issuecomment-1225532241

**Comment by kopax-polyconseil** [comment] 2023-06-06 14:26
> > Any PR tu spport new feature are welcome !
> 
> That ship has sailed, we already found another vendor.

Feel free to drop the link here for others :)

**Comment by leslierhsw** [comment] 2023-06-06 15:03
> 



> > > Any PR tu spport new feature are welcome !
> > 
> > 
> > That ship has sailed, we already found another vendor.
> 
> Feel free to drop the link here for others :)

And that ship has sailed... too. I moved to another task. Looks like an in-house service and component. My teammates are working on this with the author.

**Comment by josepmiquel-exilium** [comment] 2024-02-26 23:40
If someone is experiencing the same issue, I've found the solution after many hours of testing EVERYTHING.

- Uninstall this library, due that it's not needed anymore.
- Put this script on THE TOP (this is very important) of the body inside the index.html (remember to replace the ID):
```
    <script
      id="Cookiebot"
      src="https://consent.cookiebot.com/uc.js"
      data-cbid=<<YOUR ID>>
      type="text/javascript"
      .
      data-blockingmode="auto"
    ></script>
```
- Create a component where you want to render the Cookiebot Declaration with the following code (remember to replace the ID again):
```
import { useEffect, useRef } from 'react';

function Component() {
  const legalContainerRef = useRef(null);

  useEffect(() => {
    const script = document.createElement('script');
    script.id = 'CookieDeclaration';
    script.src = 'https://consent.cookiebot.com/<<YOUR ID>>/cd.js';
    script.type = 'text/javascript';
    script.async = true;

    legalContainerRef.current.appendChild(script);

    return () => {
      legalContainerRef.current.removeChild(script);
    };
  }, [legalContainerRef]);

  return (
      <div ref={legalContainerRef} className="legal__container" />
  );
}

export default Component;
```
Et voilà!

**Comment by kopax** [comment] 2024-02-27 14:51
Pull request are welcome ! :)
